include:
  - template: Auto-DevOps.gitlab-ci.yml

publish:
  stage: production
  image: registry.wukl.net/wukl/cert-manager-webhook-openprovider/publish-image:1
  script:
    - helm package deploy/openprovider-webhook
    - VERSION=$(yq -r .version < deploy/openprovider-webhook/Chart.yaml)
    - >
      curl 
      --request POST 
      --user gitlab-ci-token:$CI_JOB_TOKEN 
      --form "chart=@openprovider-webhook-${VERSION}.tgz" 
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${CHANNEL}/charts"
  variables:
    CHANNEL: master
