// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthLoginResponseData LoginResponseData
// Example: {"reseller_id":123456,"token":"20d65561c9636d262e59aec8582c20c7"}
//
// swagger:model authLoginResponseData
type AuthLoginResponseData struct {

	// The reseller id
	ResellerID int32 `json:"reseller_id,omitempty"`

	// The token
	Token string `json:"token,omitempty"`
}

// Validate validates this auth login response data
func (m *AuthLoginResponseData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth login response data based on context it is used
func (m *AuthLoginResponseData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthLoginResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthLoginResponseData) UnmarshalBinary(b []byte) error {
	var res AuthLoginResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
