// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthLoginRequest LoginRequest
// Example: {"ip":"123.123.123.123","password":"eivr4ReKoz","username":"openprovider"}
//
// swagger:model authLoginRequest
type AuthLoginRequest struct {

	// The IP address (0.0.0.0 is any IP address)
	IP string `json:"ip,omitempty"`

	// The user's password
	Password string `json:"password,omitempty"`

	// The user's name
	Username string `json:"username,omitempty"`
}

// Validate validates this auth login request
func (m *AuthLoginRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth login request based on context it is used
func (m *AuthLoginRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthLoginRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthLoginRequest) UnmarshalBinary(b []byte) error {
	var res AuthLoginRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
