// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorWarning Warning
// Example: {"code":0,"data":"","desc":""}
//
// swagger:model errorWarning
type ErrorWarning struct {

	// Warning code
	Code int32 `json:"code,omitempty"`

	// Additional warning description
	Data string `json:"data,omitempty"`

	// Warning description
	Desc string `json:"desc,omitempty"`
}

// Validate validates this error warning
func (m *ErrorWarning) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error warning based on context it is used
func (m *ErrorWarning) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorWarning) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorWarning) UnmarshalBinary(b []byte) error {
	var res ErrorWarning
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
