// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorError Error
// Example: {"code":0,"data":"","desc":""}
//
// swagger:model errorError
type ErrorError struct {

	// Error code
	Code int32 `json:"code,omitempty"`

	// Additional error description
	Data string `json:"data,omitempty"`

	// Error description
	Desc string `json:"desc,omitempty"`
}

// Validate validates this error error
func (m *ErrorError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this error error based on context it is used
func (m *ErrorError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorError) UnmarshalBinary(b []byte) error {
	var res ErrorError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
