// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HistoryZoneHistory ZoneHistory
// Example: {"date":"2019-06-19 17:40:09","is":"+ A |  | 8.8.8.8","source":"","was":""}
//
// swagger:model historyZoneHistory
type HistoryZoneHistory struct {

	// Date of operation
	Date string `json:"date,omitempty"`

	// New value
	Is string `json:"is,omitempty"`

	// The source
	Source string `json:"source,omitempty"`

	// Old value
	Was string `json:"was,omitempty"`
}

// Validate validates this history zone history
func (m *HistoryZoneHistory) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this history zone history based on context it is used
func (m *HistoryZoneHistory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HistoryZoneHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HistoryZoneHistory) UnmarshalBinary(b []byte) error {
	var res HistoryZoneHistory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
