// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecordRecordInfo RecordInfo
// Example: {"creation_date":"","ip":"127.0.0.1","modification_date":"","name":"domain.com","prio":1,"ttl":900,"type":"CNAME","value":"abcd.domain.com"}
//
// swagger:model recordRecordInfo
type RecordRecordInfo struct {

	// DNS record creation date
	CreationDate string `json:"creation_date,omitempty"`

	// DNS record IP address
	IP string `json:"ip,omitempty"`

	// DNS record last modification date
	ModificationDate string `json:"modification_date,omitempty"`

	// DNS record name
	Name string `json:"name,omitempty"`

	// DNS record priority
	Prio int32 `json:"prio,omitempty"`

	// DNS record priority
	TTL int32 `json:"ttl,omitempty"`

	// DNS record type
	Type string `json:"type,omitempty"`

	// DNS record value
	Value string `json:"value,omitempty"`
}

// Validate validates this record record info
func (m *RecordRecordInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this record record info based on context it is used
func (m *RecordRecordInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecordRecordInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecordRecordInfo) UnmarshalBinary(b []byte) error {
	var res RecordRecordInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
