// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZoneDomain Domain
// Example: {"extension":"com","name":"domain"}
//
// swagger:model zoneDomain
type ZoneDomain struct {

	// Domain extension
	Extension string `json:"extension,omitempty"`

	// Domain name without extension
	Name string `json:"name,omitempty"`
}

// Validate validates this zone domain
func (m *ZoneDomain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this zone domain based on context it is used
func (m *ZoneDomain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZoneDomain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneDomain) UnmarshalBinary(b []byte) error {
	var res ZoneDomain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
