// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZoneRecord Record
// Example: {"name":"domain.com","prio":1,"ttl":900,"type":"CNAME","value":"abcd.domain.com"}
//
// swagger:model zoneRecord
type ZoneRecord struct {

	// DNS record name
	Name string `json:"name,omitempty"`

	// DNS record priority
	Prio int32 `json:"prio,omitempty"`

	// DNS record priority
	TTL int32 `json:"ttl,omitempty"`

	// DNS record type
	Type string `json:"type,omitempty"`

	// DNS record value
	Value string `json:"value,omitempty"`
}

// Validate validates this zone record
func (m *ZoneRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this zone record based on context it is used
func (m *ZoneRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZoneRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneRecord) UnmarshalBinary(b []byte) error {
	var res ZoneRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
