// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZoneListZonesResponse ListZonesResponse
// Example: {"code":0,"data":{"results":[{"active":true,"creation_date":"2012-02-05 7:37:28","dnskey":"","history":[{"date":"2019-06-19 17:40:09","is":true,"source":"","was":""}],"id":12345,"ip":"127.0.0.1","is_deleted":false,"is_shadow":false,"is_spamexperts_enabled":false,"modification_date":"2018-11-28 6:57:05","name":"domain.com","premium_dns":{"sectigo":{"autorenew":false,"order_date":"2021-08-05 7:37:28","renewal_date":"2022-11-28 6:57:05","secured":false,"website_id":123456}},"provider":"sectigo","records":[{"creation_date":"","ip":"127.0.0.1","modification_date":"","name":"domain.com","prio":1,"ttl":900,"type":"CNAME","value":"abcd.domain.com"}],"reseller_id":123456,"type":"master"}],"total":1888},"desc":""}
//
// swagger:model zoneListZonesResponse
type ZoneListZonesResponse struct {

	// Response code
	Code int32 `json:"code,omitempty"`

	// Response data
	Data *ZoneListZonesResponseData `json:"data,omitempty"`

	// Response description
	Desc string `json:"desc,omitempty"`

	// Indicates if Openprovider API is on maintenance
	Maintenance bool `json:"maintenance,omitempty"`

	// Array of warning messages
	Warnings []*ErrorWarning `json:"warnings"`
}

// Validate validates this zone list zones response
func (m *ZoneListZonesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarnings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZoneListZonesResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

func (m *ZoneListZonesResponse) validateWarnings(formats strfmt.Registry) error {
	if swag.IsZero(m.Warnings) { // not required
		return nil
	}

	for i := 0; i < len(m.Warnings); i++ {
		if swag.IsZero(m.Warnings[i]) { // not required
			continue
		}

		if m.Warnings[i] != nil {
			if err := m.Warnings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("warnings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("warnings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this zone list zones response based on the context it is used
func (m *ZoneListZonesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWarnings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZoneListZonesResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if m.Data != nil {
		if err := m.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

func (m *ZoneListZonesResponse) contextValidateWarnings(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Warnings); i++ {

		if m.Warnings[i] != nil {
			if err := m.Warnings[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("warnings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("warnings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ZoneListZonesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneListZonesResponse) UnmarshalBinary(b []byte) error {
	var res ZoneListZonesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
