// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZoneSectigoData SectigoData
// Example: {"autorenew":false,"order_date":"2021-08-05 7:37:28","renewal_date":"2022-11-28 6:57:05","secured":false,"website_id":123456}
//
// swagger:model zoneSectigoData
type ZoneSectigoData struct {

	// Desired autorenew value
	Autorenew bool `json:"autorenew,omitempty"`

	// Premium DNS order creation date
	OrderDate string `json:"order_date,omitempty"`

	// Premium DNS order renewal date
	RenewalDate string `json:"renewal_date,omitempty"`

	// Used to enable or disable DNSSEC for this DNS zone
	Secured bool `json:"secured,omitempty"`

	// Premium DNS zone external ID
	WebsiteID int32 `json:"website_id,omitempty"`
}

// Validate validates this zone sectigo data
func (m *ZoneSectigoData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this zone sectigo data based on context it is used
func (m *ZoneSectigoData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZoneSectigoData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZoneSectigoData) UnmarshalBinary(b []byte) error {
	var res ZoneSectigoData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
