// Code generated by go-swagger; DO NOT EDIT.

package zone_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wukl.net/projects/cert-manager-webhook-openprovider/opapi/models"
)

// CreateZoneReader is a Reader for the CreateZone structure.
type CreateZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateZoneOK creates a CreateZoneOK with default headers values
func NewCreateZoneOK() *CreateZoneOK {
	return &CreateZoneOK{}
}

/*
CreateZoneOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateZoneOK struct {
	Payload *models.ZoneZoneBoolResponse
}

// IsSuccess returns true when this create zone o k response has a 2xx status code
func (o *CreateZoneOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create zone o k response has a 3xx status code
func (o *CreateZoneOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create zone o k response has a 4xx status code
func (o *CreateZoneOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create zone o k response has a 5xx status code
func (o *CreateZoneOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create zone o k response a status code equal to that given
func (o *CreateZoneOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create zone o k response
func (o *CreateZoneOK) Code() int {
	return 200
}

func (o *CreateZoneOK) Error() string {
	return fmt.Sprintf("[POST /v1beta/dns/zones][%d] createZoneOK  %+v", 200, o.Payload)
}

func (o *CreateZoneOK) String() string {
	return fmt.Sprintf("[POST /v1beta/dns/zones][%d] createZoneOK  %+v", 200, o.Payload)
}

func (o *CreateZoneOK) GetPayload() *models.ZoneZoneBoolResponse {
	return o.Payload
}

func (o *CreateZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZoneZoneBoolResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateZoneDefault creates a CreateZoneDefault with default headers values
func NewCreateZoneDefault(code int) *CreateZoneDefault {
	return &CreateZoneDefault{
		_statusCode: code,
	}
}

/*
CreateZoneDefault describes a response with status code -1, with default header values.

(empty)
*/
type CreateZoneDefault struct {
	_statusCode int

	Payload *models.ErrorError
}

// IsSuccess returns true when this create zone default response has a 2xx status code
func (o *CreateZoneDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create zone default response has a 3xx status code
func (o *CreateZoneDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create zone default response has a 4xx status code
func (o *CreateZoneDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create zone default response has a 5xx status code
func (o *CreateZoneDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create zone default response a status code equal to that given
func (o *CreateZoneDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create zone default response
func (o *CreateZoneDefault) Code() int {
	return o._statusCode
}

func (o *CreateZoneDefault) Error() string {
	return fmt.Sprintf("[POST /v1beta/dns/zones][%d] CreateZone default  %+v", o._statusCode, o.Payload)
}

func (o *CreateZoneDefault) String() string {
	return fmt.Sprintf("[POST /v1beta/dns/zones][%d] CreateZone default  %+v", o._statusCode, o.Payload)
}

func (o *CreateZoneDefault) GetPayload() *models.ErrorError {
	return o.Payload
}

func (o *CreateZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
