// Code generated by go-swagger; DO NOT EDIT.

package zone_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wukl.net/projects/cert-manager-webhook-openprovider/opapi/models"
)

// GetZoneReader is a Reader for the GetZone structure.
type GetZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetZoneOK creates a GetZoneOK with default headers values
func NewGetZoneOK() *GetZoneOK {
	return &GetZoneOK{}
}

/*
GetZoneOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetZoneOK struct {
	Payload *models.ZoneGetZoneResponse
}

// IsSuccess returns true when this get zone o k response has a 2xx status code
func (o *GetZoneOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get zone o k response has a 3xx status code
func (o *GetZoneOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get zone o k response has a 4xx status code
func (o *GetZoneOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get zone o k response has a 5xx status code
func (o *GetZoneOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get zone o k response a status code equal to that given
func (o *GetZoneOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get zone o k response
func (o *GetZoneOK) Code() int {
	return 200
}

func (o *GetZoneOK) Error() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones/{name}][%d] getZoneOK  %+v", 200, o.Payload)
}

func (o *GetZoneOK) String() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones/{name}][%d] getZoneOK  %+v", 200, o.Payload)
}

func (o *GetZoneOK) GetPayload() *models.ZoneGetZoneResponse {
	return o.Payload
}

func (o *GetZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZoneGetZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetZoneDefault creates a GetZoneDefault with default headers values
func NewGetZoneDefault(code int) *GetZoneDefault {
	return &GetZoneDefault{
		_statusCode: code,
	}
}

/*
GetZoneDefault describes a response with status code -1, with default header values.

(empty)
*/
type GetZoneDefault struct {
	_statusCode int

	Payload *models.ErrorError
}

// IsSuccess returns true when this get zone default response has a 2xx status code
func (o *GetZoneDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get zone default response has a 3xx status code
func (o *GetZoneDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get zone default response has a 4xx status code
func (o *GetZoneDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get zone default response has a 5xx status code
func (o *GetZoneDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get zone default response a status code equal to that given
func (o *GetZoneDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get zone default response
func (o *GetZoneDefault) Code() int {
	return o._statusCode
}

func (o *GetZoneDefault) Error() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones/{name}][%d] GetZone default  %+v", o._statusCode, o.Payload)
}

func (o *GetZoneDefault) String() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones/{name}][%d] GetZone default  %+v", o._statusCode, o.Payload)
}

func (o *GetZoneDefault) GetPayload() *models.ErrorError {
	return o.Payload
}

func (o *GetZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
