// Code generated by go-swagger; DO NOT EDIT.

package zone_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wukl.net/projects/cert-manager-webhook-openprovider/opapi/models"
)

// ListZonesReader is a Reader for the ListZones structure.
type ListZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListZonesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListZonesOK creates a ListZonesOK with default headers values
func NewListZonesOK() *ListZonesOK {
	return &ListZonesOK{}
}

/*
ListZonesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListZonesOK struct {
	Payload *models.ZoneListZonesResponse
}

// IsSuccess returns true when this list zones o k response has a 2xx status code
func (o *ListZonesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list zones o k response has a 3xx status code
func (o *ListZonesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list zones o k response has a 4xx status code
func (o *ListZonesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list zones o k response has a 5xx status code
func (o *ListZonesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list zones o k response a status code equal to that given
func (o *ListZonesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list zones o k response
func (o *ListZonesOK) Code() int {
	return 200
}

func (o *ListZonesOK) Error() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones][%d] listZonesOK  %+v", 200, o.Payload)
}

func (o *ListZonesOK) String() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones][%d] listZonesOK  %+v", 200, o.Payload)
}

func (o *ListZonesOK) GetPayload() *models.ZoneListZonesResponse {
	return o.Payload
}

func (o *ListZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZoneListZonesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListZonesDefault creates a ListZonesDefault with default headers values
func NewListZonesDefault(code int) *ListZonesDefault {
	return &ListZonesDefault{
		_statusCode: code,
	}
}

/*
ListZonesDefault describes a response with status code -1, with default header values.

(empty)
*/
type ListZonesDefault struct {
	_statusCode int

	Payload *models.ErrorError
}

// IsSuccess returns true when this list zones default response has a 2xx status code
func (o *ListZonesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list zones default response has a 3xx status code
func (o *ListZonesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list zones default response has a 4xx status code
func (o *ListZonesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list zones default response has a 5xx status code
func (o *ListZonesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list zones default response a status code equal to that given
func (o *ListZonesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list zones default response
func (o *ListZonesDefault) Code() int {
	return o._statusCode
}

func (o *ListZonesDefault) Error() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones][%d] ListZones default  %+v", o._statusCode, o.Payload)
}

func (o *ListZonesDefault) String() string {
	return fmt.Sprintf("[GET /v1beta/dns/zones][%d] ListZones default  %+v", o._statusCode, o.Payload)
}

func (o *ListZonesDefault) GetPayload() *models.ErrorError {
	return o.Payload
}

func (o *ListZonesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
