// Code generated by go-swagger; DO NOT EDIT.

package zone_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"wukl.net/projects/cert-manager-webhook-openprovider/opapi/models"
)

// UpdateZoneReader is a Reader for the UpdateZone structure.
type UpdateZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateZoneOK creates a UpdateZoneOK with default headers values
func NewUpdateZoneOK() *UpdateZoneOK {
	return &UpdateZoneOK{}
}

/*
UpdateZoneOK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdateZoneOK struct {
	Payload *models.ZoneZoneBoolResponse
}

// IsSuccess returns true when this update zone o k response has a 2xx status code
func (o *UpdateZoneOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update zone o k response has a 3xx status code
func (o *UpdateZoneOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update zone o k response has a 4xx status code
func (o *UpdateZoneOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update zone o k response has a 5xx status code
func (o *UpdateZoneOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update zone o k response a status code equal to that given
func (o *UpdateZoneOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update zone o k response
func (o *UpdateZoneOK) Code() int {
	return 200
}

func (o *UpdateZoneOK) Error() string {
	return fmt.Sprintf("[PUT /v1beta/dns/zones/{name}][%d] updateZoneOK  %+v", 200, o.Payload)
}

func (o *UpdateZoneOK) String() string {
	return fmt.Sprintf("[PUT /v1beta/dns/zones/{name}][%d] updateZoneOK  %+v", 200, o.Payload)
}

func (o *UpdateZoneOK) GetPayload() *models.ZoneZoneBoolResponse {
	return o.Payload
}

func (o *UpdateZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZoneZoneBoolResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateZoneDefault creates a UpdateZoneDefault with default headers values
func NewUpdateZoneDefault(code int) *UpdateZoneDefault {
	return &UpdateZoneDefault{
		_statusCode: code,
	}
}

/*
UpdateZoneDefault describes a response with status code -1, with default header values.

(empty)
*/
type UpdateZoneDefault struct {
	_statusCode int

	Payload *models.ErrorError
}

// IsSuccess returns true when this update zone default response has a 2xx status code
func (o *UpdateZoneDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update zone default response has a 3xx status code
func (o *UpdateZoneDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update zone default response has a 4xx status code
func (o *UpdateZoneDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update zone default response has a 5xx status code
func (o *UpdateZoneDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update zone default response a status code equal to that given
func (o *UpdateZoneDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update zone default response
func (o *UpdateZoneDefault) Code() int {
	return o._statusCode
}

func (o *UpdateZoneDefault) Error() string {
	return fmt.Sprintf("[PUT /v1beta/dns/zones/{name}][%d] UpdateZone default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateZoneDefault) String() string {
	return fmt.Sprintf("[PUT /v1beta/dns/zones/{name}][%d] UpdateZone default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateZoneDefault) GetPayload() *models.ErrorError {
	return o.Payload
}

func (o *UpdateZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
